# Generated by Django 5.1.7 on 2025-03-30 08:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('crime_id', models.AutoField(primary_key=True, serialize=False)),
                ('crime_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_committed', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('victims', models.IntegerField(default=0)),
                ('weapons_used', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('criminal_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('fingerprint_id', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='criminal_photos/')),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_number', models.CharField(max_length=50, unique=True)),
                ('investigating_officer', models.CharField(max_length=100)),
                ('evidence_details', models.TextField()),
                ('witnesses', models.TextField(blank=True)),
                ('court_dates', models.TextField(blank=True)),
                ('status', models.CharField(max_length=20)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminal_management.crime')),
            ],
        ),
        migrations.AddField(
            model_name='crime',
            name='criminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminal_management.criminal'),
        ),
        migrations.CreateModel(
            name='Arrest',
            fields=[
                ('arrest_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrest_date', models.DateTimeField()),
                ('arresting_officers', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('warrant_number', models.CharField(blank=True, max_length=50)),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminal_management.crime')),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criminal_management.criminal')),
            ],
        ),
    ]
